# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-09 07:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mail_server',
            field=models.CharField(choices=[('202.141.80.13', 'Dikrong'), ('202.141.80.12', 'Teesta'), ('202.141.80.9', 'Namboor'), ('202.141.80.10', 'Disang'), ('202.141.80.11', 'Tamdil')], max_length=50, verbose_name='mail server'),
        ),
    ]
